services:
  association:
    image: maraudr/maraudrapp:association
    ports:
      - 8080:8080
    environment:
      - Jwt__Secret=${JWT_SECRET}
      - ASSOCIATION_API_KEY=${ASSOCIATION_API_KEY}
      - GEO_API_KEY=${GEO_API_KEY}
      - STOCK_API_KEY=${STOCK_API_KEY}

  geo:
    image: maraudr/maraudrapp:geo
    ports:
      - 8084:8080
    environment:
      - GEO_API_KEY=${GEO_API_KEY}
      - ORS_API_KEY=${ORS_API_KEY} 
      - Jwt__Secret=${JWT_SECRET}
      
  stock:
    image: maraudr/maraudrapp:stock
    ports:
      - 8081:8080
    environment:
      - STOCK_API_KEY=${STOCK_API_KEY}
      - Jwt__Secret=${JWT_SECRET}
      
  user:
    image: maraudr/maraudrapp:user
    ports:
      - 8082:8080
    environment:
      - Jwt__Secret=${JWT_SECRET}
      - ApiSettings__EmailSenderApiUrl=${EMAIL_SENDER_API_URL}
      - ApiSettings__EmailSenderApiKey=${EMAIL_SENDER_API_KEY}

  mcp:
    image: maraudr/maraudrapp:mcp
    ports:
      - 8086:8080
    environment:
      - Jwt__Secret=${JWT_SECRET}
      - OpenRouter__ApiKey=${OPENROUTER_API_KEY}
      - OpenRouter__BaseUrl=${OPENROUTER_BASE_URL}
      - OpenRouter__ModelName=${OPENROUTER_MODEL_NAME}
      - ApiSettings__StockApiUrl=${STOCK_API_URL}
      - ApiSettings__PlanningApiUrl=${PLANNING_API_URL}
      - ApiSettings__AssociationUrl=${ASSOCIATION_API_URL}
      
  document:
    image: maraudr/maraudrapp:document
    ports:
      - 8087:8080
    environment:
      - Jwt__Secret=${JWT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
  
  email-sender:
    image: maraudr/maraudrapp:emailsender
    ports:
      - 8083:8080
    environment:
      - Jwt__Secret=${JWT_SECRET}
      - MailSettings__Password=${MAIL_PASSWORD}
      - MailSettings__Mail=${MAIL_ADDRESS}
      - MailSettings__Host=${MAIL_HOST}
      - MailSettings__Port=${MAIL_PORT}
      - ApiKey=${EMAIL_SENDER_API_KEY}
  
  planning:
    image: maraudr/maraudrapp:planning
    ports:
      - 8085:8080
    environment:
      - Jwt__Secret=${JWT_SECRET}
      - ASSOCIATION_API_KEY=${ASSOCIATION_API_KEY}
