services:

  maraudr-db:
    image: postgres:15
    container_name: maraudr-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maraudr-dev
    ports:
      - "5432:5432"
    volumes:
      - maraudr-db-data:/var/lib/postgresql/data
    
  association:
    build:
      context: ./src/Modules/Maraudr.Association/
      target: final
    ports:
      - 8080:8080
    depends_on:
      - maraudr-db

  geo:
    build:
      context: ./src/Modules/Maraudr.Geo/
      target: final
    ports:
      - 8084:8080
    depends_on:
      - maraudr-db

  stock:
    build:
      context: ./src/Modules/Maraudr.Stock/
      target: final
    ports:
      - 8081:8080
    environment:
      - Jwt__Secret=azjaeiaeuhaeuohehuoeauohaehuoaehuoaeuhoaeuhaehuo
    depends_on:
      - maraudr-db

  user:
    build:
      context: ./src/Modules/Maraudr.User/
      target: final
    ports:
      - 8082:8080
    environment:
      - Jwt__Secret=azjaeiaeuhaeuohehuoeauohaehuoaehuoaeuhoaeuhaehuo
      - ApiSettings__EmailSenderApiUrl=http://email-sender:8080/ 
    depends_on:
      - maraudr-db

  email-sender:
    build:
      context: ./src/Modules/Maraudr.EmailSender/
      target: final
    ports:
      - 8083:8080
    environment:
      - Jwt__Secret=azjaeiaeuhaeuohehuoeauohaehuoaehuoaeuhoaeuhaehuo
      - MailSettings__Password=
      - MailSettings__Mail=
      - MailSettings__Host=smtp.mailersend.net
      - MailSettings__Port=587
    depends_on:
      - maraudr-db
  
volumes:
  maraudr-db-data: