services:


  association:
    build:
      context: ./src/Modules/Maraudr.Association/
      target: final
    ports:
      - 8080:8080
    environment:
      - Jwt__Secret=azjaeiaeuhaeuohehuoeauohaehuoaehuoaeuhoaeuhaehuo
      - ASSOCIATION_API_KEY=amiralcommandergrossetttttttt2222222228
    

  geo:
    build:
      context: ./src/Modules/Maraudr.Geo/
      target: final
    ports:
      - 8084:8080
    environment:
      - Jwt__Secret=azjaeiaeuhaeuohehuoeauohaehuoaehuoaeuhoaeuhaehuo  
  

  stock:
    build:
      context: ./src/Modules/Maraudr.Stock/
      target: final
    ports:
      - 8081:8080
    environment:
      - Jwt__Secret=azjaeiaeuhaeuohehuoeauohaehuoaehuoaeuhoaeuhaehuo
    
  user:
    build:
      context: ./src/Modules/Maraudr.User/
      target: final
    ports:
      - 8082:8080
    environment:
      - Jwt__Secret=azjaeiaeuhaeuohehuoeauohaehuoaehuoaeuhoaeuhaehuo
      - ApiSettings__EmailSenderApiUrl=http://email-sender:8080/ 


  email-sender:
    build:
      context: ./src/Modules/Maraudr.EmailSender/
      target: final
    ports:
      - 8083:8080
    environment:
      - Jwt__Secret=azjaeiaeuhaeuohehuoeauohaehuoaehuoaeuhoaeuhaehuo
      - MailSettings__Password=
      - MailSettings__Mail=
      - MailSettings__Host=smtp.mailersend.net
      - MailSettings__Port=587
  
  planning:
    build:
      context: ./src/Modules/Maraudr.Planning/
      target: final
    ports:
      - 8085:8080
    environment:
      - Jwt__Secret=azjaeiaeuhaeuohehuoeauohaehuoaehuoaeuhoaeuhaehuo
      - ASSOCIATION_API_KEY=amiralcommandergrossetttttttt2222222228
    
  
      