name: Build and Push Docker Images

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_PREFIX: maraudr/maraudrapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Association module
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.Association
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-association:latest

      - name: Build and push Authentication module
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.Authentication
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-authentication:latest

      - name: Build and push EmailSender module
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.EmailSender
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-emailsender:latest

      - name: Build and push Geo module
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.Geo
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-geo:latest

      - name: Build and push Stock module
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.Stock
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-stock:latest

      - name: Build and push User module
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.User
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-user:latest
