name: Build and Push Docker Images

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: maraudr/maraudrapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Association
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.Association
          push: true
          tags: ${{ env.IMAGE_REPO }}:association-latest

      - name: Build and push Authentication
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.Authentication
          push: true
          tags: ${{ env.IMAGE_REPO }}:authentication-latest

      - name: Build and push EmailSender
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.EmailSender
          push: true
          tags: ${{ env.IMAGE_REPO }}:emailsender-latest

      - name: Build and push Geo
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.Geo
          push: true
          tags: ${{ env.IMAGE_REPO }}:geo-latest

      - name: Build and push Stock
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.Stock
          push: true
          tags: ${{ env.IMAGE_REPO }}:stock-latest

      - name: Build and push User
        uses: docker/build-push-action@v5
        with:
          context: ./src/Modules/Maraudr.User
          push: true
          tags: ${{ env.IMAGE_REPO }}:user-latest
